Fix fatal exception since onDestroy() did not call through to super.onDestroy()
E/AndroidRuntime: FATAL EXCEPTION: main
Process: chengyihe.com.screentimeout, PID: 30561
android.util.SuperNotCalledException: Activity {chengyihe.com.screentimeout/chengyihe.com.screentimeout.MainActivity} did not call through to super.onDestroy()
at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4141)
at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4170)
at android.app.ActivityThread.access$1500(ActivityThread.java:150)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:168)
at android.app.ActivityThread.main(ActivityThread.java:5845)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)